export const GET_LIST_CATEGORYMOVIE_REQUEST = "GET_LIST_CATEGORYMOVIE_REQUEST";
export const GET_LIST_CATEGORYMOVIE_SUCCESS = "GET_LIST_CATEGORYMOVIE_SUCCESS";
export const GET_LIST_CATEGORYMOVIE_FAILURE = "GET_LIST_CATEGORYMOVIE_FAILURE";
